version: "3.9"
services:
  api:
    container_name: dev1
    build: ./dev1/
    ports: 
      - "8000:8000"
    volumes:
      - type: volume
        source: dev1-vol
        target: /app
volumes:
  dev1-vol: {}
